### ISSUE TITLE
App needs to be updated to continue syncing with Health Connect

### ISSUE THREAD

**Issue by jackvintedge** [S-HealthStack/starter-app#3]
Hi,

I have run the project in the emulator with the following specs:
Android 14 ("UpsideDownCake") | x86_64

It run successfully but it hit the following pop up to mentioned that the app needs to be updated to continue syncing with Health Connect. 
![image](https://github.com/S-HealthStack/starter-app/assets/50222734/b2b822ec-1e4e-4209-bf8e-02cb9a2a5c47)

Please advise if there is any solution for this.

Thanks.

**Comment by jackvintedge** [comment]
Hi, any update on this issue? Please let me know if there is any further information needed from my side.

**Comment by jjyun-do** [comment]
@jackvintedge 

Hello.
First of all, the Health Connect has been updated in Android 14. 
From Android 14, it is included in Android system, and not a separate app anymore.

Currently, HealthStack is compatible with Android 13 and are trying to provide compatibility with Android 14 as well.

You can refer to the guide below, and we'll appreciate if you contribute :)

- https://support.google.com/android/answer/14119325?hl=en
- https://developer.android.com/health-and-fitness/guides/health-connect/develop/get-started?hl=en

**Comment by Jade-H** [comment]
🚫 Issue closed. Thank you for the contribution.
